### PR TITLE
setup.py: don't forget to install packages.

### LINKED ISSUE #32: No module named usbrply.parsers
Hi, I've been struggling with making all of this work for a few days.

Been launching setup.py to build & install.
Then when launching with a pcapng file, got this error on line 4, when importing : 

ImportError : no module named usbrply.parsers

But the parser python file is present in the folder, did I builded something wrong ?

When launching directly from the usbrply.py file, after adding the usbrply to the path, I get the 'Cannot import name sockaddr_in' error.

Maybe this is evident for python coders, but for example, the main.py script should be renamed usbrply.py, I've also been struggling with this for a few minutes before understanding it had to be renamed. (this also crash the pip install)

### PR DESCRIPTION
**Pull request by krasin**
Hi John,

this is a lame attempt to fix #32. I don't have full confidence that it does the trick, because my system is Python3 and the mainline usbrply is broken for me due to #9. But I have some hope that my patch makes it better.

Please, don't merge until somebody confirms that it resolved the issue for them.

### CODE REVIEW

**Comment by JohnDMcMaster** [comment]
I was able to reproduce the issue on a vm and confirmed your patch fixes it. Thanks!

**Comment by krasin** [comment]
Great! Thank you for checking and merging it, @JohnDMcMaster!
